// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Index from "./Index.res.js";
import * as Nodemodule from "node:module";
import WebTreeSitter from "web-tree-sitter";
import * as Promises from "node:fs/promises";

await WebTreeSitter.init();

var parser = new WebTreeSitter();

console.log(parser);

var file = await Promises.readFile("./test.py", "utf-8");

console.log(file);

var $$require = Nodemodule.createRequire(import.meta.url);

var wasmPath = $$require.resolve("tree-sitter-wasms/out/tree-sitter-python.wasm");

var language = await WebTreeSitter.Language.load(wasmPath);

parser.setLanguage(language);

var query = language.query(Index.getScmQuery("python"));

var tree = parser.parse(file);

var rootNode = tree.rootNode;

var captures = query.captures(rootNode);

console.log(captures);

export {
  parser ,
  file ,
  $$require ,
  wasmPath ,
  language ,
  query ,
  tree ,
  rootNode ,
  captures ,
}
/*  Not a pure module */
