// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Index from "./Index.res.js";
import * as Core__Promise from "@rescript/core/src/Core__Promise.res.js";

function testOutlineAsync() {
  console.log("Testing getOutlineAsync with test.py...");
  return Core__Promise.$$catch(Index.getOutlineAsync("./test.py").then(function (result) {
                  if (result.TAG === "Ok") {
                    console.log("Successfully generated outline:");
                    console.log(result._0);
                  } else {
                    console.log("Failed to generate outline:");
                    console.log(result._0);
                  }
                  return Promise.resolve();
                }), (function (param) {
                console.log("Error during outline generation");
                return Promise.resolve();
              }));
}

testOutlineAsync();

export {
  testOutlineAsync ,
}
/*  Not a pure module */
